### ISSUE TITLE
11.2 about refactoring checklist

### ISSUE THREAD

**Issue by sinri0809** [sinri0809/sinristory#4]
특별히 신경써야 할 부분들  

- [ ]  fetch 페이지 들어가면 한번만 할 수 있도록...  
- [ ] 이미지 로딩 시간이 좀 긴거 같음...  
- [ ] css 파일 정리해야뎀
